// Code generated by actorgen .; DO NOT EDIT.

package main

import "context"

func NewActor(p *Player) *Actor {
	ctx, cancel := context.WithCancel(context.Background())
	return &Actor{
		p:       p,
		mailbox: make(chan chan interface{}, 256),
		ctx:     ctx,
		cancel:  cancel,
		join:    make(chan interface{}),
	}
}

type Actor struct {
	p       *Player
	mailbox chan chan interface{}
	ctx     context.Context
	cancel  context.CancelFunc
	join    chan interface{}
}

func (a *Actor) Start() {
	go a.run()
}

func (a *Actor) run() {
runLoop:
	for {
		select {
		case <-a.ctx.Done():
			close(a.join)
			break runLoop
		case m := <-a.mailbox:
			m <- struct{}{}
		}
	}
}

func (a *Actor) Stop() {
	a.cancel()
	<-a.join
}

func (a *Actor) Attack() {
	m := make(chan interface{})
	a.mailbox <- m
	<-m
	close(m)
	a.p.Attack()
}

func (a *Actor) Heal() bool {
	m := make(chan interface{})
	a.mailbox <- m
	<-m
	close(m)
	return a.p.Heal()
}
